### ISSUE TITLE
AttributeError: partially initialized module 'services' has no attribute 'jobs' (most likely due to a circular import)

### ISSUE THREAD

**Issue by menotuu** [Mastaaa1987/vxparser#7]
Windows 11 24H2 26100.712 + Python 3.12.3 WinStore Version

installiert über cmd > "python3 -m pip install vxparser", gestartet mit Doppelklick auf C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\vxparser.exe
dabei kommt folgendes heraus.....
ich kann mich im Menü bewegen und wähle "Vavoo (LiveTV)" aus > "Get LiveTV Lists": 
[PROCESS][M3U8]:: Starting with URL: http://192.168.1.24:8080 ...
creating Albania.m3u8 ...
(...)
creating Germany.m3u8 ...
creating Italy.m3u8 ...
(...)
nach 2 Minuten dann [PROCESS][M3U8]:: Done!

aber der Ordner ist leer.Bin ich zu blöd? Die .m3u sollte doch jetzt im Verzeichnis auftauchen wo sich der vxparser.exe befindet - nicht?

`INFO:     Will watch for changes in these directories: ['C:\\Users\\Packy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\Scripts']
[SERVICE][API]:: Successful started...
[SERVICE][M3U8]:: Successful started...
[SERVICE][EPG]:: Successful started...
[?] Main Menu:
 >
   Settings =>
   Vavoo (LiveTV) =>
   Xstream (VoD's & Series) =>
   Stop Services
   Restart Services
   - Clean Database (Settings)
   - Clear Cache Path
   <= Shutdown
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\utils\xstream.py", line 12, in <module>
    import services
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
ImportError: cannot import name 'UvicornServer' from partially initialized module 'api' (most likely due to a circular import) (C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\api.py)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\utils\xstream.py", line 21, in <module>
    jobs = services.jobs
           ^^^^^^^^^^^^^
AttributeError: partially initialized module 'services' has no attribute 'jobs' (most likely due to a circular import)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\Packy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\vxparser\utils\xstream.py", line 21, in <module>
    jobs = services.jobs
           ^^^^^^^^^^^^^
AttributeError: partially initialized module 'services' has no attribute 'jobs' (most likely due to a circular import)
`

**Comment by casaqori** [comment]
probier mal ob ein versionsupdate hilft:
python3 -m pip install vxparser===1.3.8

**Comment by kkbasel44** [comment]
**Umgebung**
_Betriebssystem_
Edition: Windows 11 Pro
Version: 23H2
Installiert am: 22.‎09.‎2022
Betriebssystembuild: 22631.3737
Leistung:	Windows Feature Experience Pack 1000.22700.1009.0

_Python_
Python: 3.11.1
PIP: 24.1.1
vxparser: 1.3.8
Installiert mit `py -m pip install vxparser`

**Fehlerbeschreibung**
- Start in der Powershell mit `py -m vxparser`
-  Startet erst normal und das Menü wird sichtbar
- Nach ca. 2 Sekunden erscheint folgende vergleichbare Fehlermeldung

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\utils\xstream.py", line 12, in <module>
    import services
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
ImportError: cannot import name 'UvicornServer' from partially initialized module 'api' (most likely due to a circular import) (C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\api.py)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\utils\xstream.py", line 21, in <module>
    jobs = services.jobs
           ^^^^^^^^^^^^^
AttributeError: partially initialized module 'services' has no attribute 'jobs' (most likely due to a circular import)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\services.py", line 9, in <module>
    from api import UvicornServer
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\api.py", line 16, in <module>
    import utils.xstream as xstream
  File "C:\Users\$$$Extra_Ersetzt$$$\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\utils\xstream.py", line 21, in <module>
    jobs = services.jobs
           ^^^^^^^^^^^^^
AttributeError: partially initialized module 'services' has no attribute 'jobs' (most likely due to a circular import)
```
- Benutzername oben ist unkenntlich mit `$$$Extra_Ersetzt$$$` unkenntlich gemacht worden
- Nach Tastendruck ist man wieder im Menü
- Listenerstellung über Vavoo (LiveTV) funktioniert und werden abgegelgt unter `...\AppData\Local\Programs\Python\Python311\Lib\site-packages\vxparser\data\lists`

**Comment by Mastaaa1987** [comment]
Das die pypi package wohl am ehesten funktioniert liegt bestimmt daran das ich den vxparser schon immer als pypi package vorgesehen habe ... Aber warum du so massive probleme hast liegt wohl daran das du windows nutzt ... Habe den vxparser auf unix ausgelegt deshalb musst du unter windoof das Linux Subsystem nutzen... Wennde in ubuntu pip install vxparser eingibst läuft alles mehr als tadellos ... Mit windows haste schon multiprocess probleme und lagg times auf grund dessen, das lange nicht mehr feierlich ....
Das aber nur so am Rande vom entwickler :-P
