### ISSUE TITLE
VoD Suche schlägt fehl

### ISSUE THREAD

**Issue by viruz82** [Mastaaa1987/vxparser#9]
Moin,

die Suche fällt auf die Nase - zumindest bei der Nutzung von Leerzeichen.

Das Ging auf jeden Fall früher mal. :D

`Traceback (most recent call last):
  File "/opt/vxparser/vxparser/main.py", line 20, in <module>
    main()
  File "/opt/vxparser/vxparser/main.py", line 16, in main
    cli.menu()
  File "/opt/vxparser/vxparser/cli.py", line 298, in menu
    ser = xstream.search(quest['item'])
  File "/opt/vxparser/vxparser/utils/xstream.py", line 298, in search
    load = site.search(search)
  File "/opt/vxparser/vxparser/helper/sites/cinemathek.py", line 261, in search
    find = showEntries(URL_SEARCH % cParser().quotePlus(sSearchText), sSearchText)
  File "/opt/vxparser/vxparser/helper/sites/cinemathek.py", line 61, in showEntries
    sHtmlContent = oRequest.request()
  File "/opt/vxparser/vxparser/helper/requestHandler.py", line 120, in request
    oResponse = opener.open(oRequest)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out`

**Comment by Mastaaa1987** [comment]
Ja müsste Mal schauen dass ich bisschen uptodate bleibe vill aber xstream addon ist hart verschlüsselt und irgendwie noch kein Bock bisher mich damit aus ein ander zu setzen..
Mache gerade in Crypto Trading und so
